[project]
name = "skypydb"
version = "0.1.0"
authors = [{name = "Ahen Studio"}]
description = "Open-source Reactive Python database"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License"]
dependencies = [
    "reflex>=0.8.25",
    "uvicorn>=0.23.0",
]

[project.urls]
"Homepage" = "https://github.com/Ahen-Studio/skypy-db"
"Bug Tracker" = "https://github.com/Ahen-Studio/skypy-db/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"