[package]
name = "mesosphere-db-connection"
version = "2.0.0"
edition = "2021"

[dependencies]
mesosphere-application = { path = "../application" }
mesosphere-errors = { path = "../errors" }
sqlx = { version = "0.8", default-features = false, features = ["mysql", "runtime-tokio-rustls"] }
