[package]
name = "mesosphere-errors"
version = "2.0.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", default-features = false, features = ["mysql"] }
thiserror = "2"
